[project]
name = "bitstake"
requirements = []
authors = []
telemetry = false

[contracts.bitstake-pool-registry]
path = "contracts/bitstake-pool-registry.clar"
clarity_version = 2
epoch = "2.5"

[contracts.bitstake-pool-deposits]
path = "contracts/bitstake-pool-deposits.clar"
clarity_version = 2
epoch = "2.5"

[contracts.bitstake-lbstx]
path = "contracts/bitstake-lbstx.clar"
clarity_version = 2
epoch = "2.5"

[contracts.bitstake-bbstx]
path = "contracts/bitstake-bbstx.clar"
clarity_version = 2
epoch = "2.5"

[contracts.bitstake-mbstx]
path = "contracts/bitstake-mbstx.clar"
clarity_version = 2
epoch = "2.5"

[contracts.bitstake-rewards]
path = "contracts/bitstake-rewards.clar"
clarity_version = 2
epoch = "2.5"

[contracts.bitstake-bstx-oracle]
path = "contracts/bitstake-bstx-oracle.clar"
clarity_version = 2
epoch = "2.5"

[contracts.bitstake-bstx-oracle-twap]
path = "contracts/bitstake-bstx-oracle-twap.clar"
clarity_version = 2
epoch = "2.5"

[contracts.bitstake-oracle-circuit-breaker]
path = "contracts/bitstake-oracle-circuit-breaker.clar"
clarity_version = 2
epoch = "2.5"

[contracts.bitstake-alex-governance]
path = "contracts/bitstake-alex-governance.clar"
clarity_version = 2
epoch = "2.5"

[contracts.bitstake-bitflow-pool]
path = "contracts/bitstake-bitflow-pool.clar"
clarity_version = 2
epoch = "2.5"

[[deployment_plan.genesis]]
